# Generated by Django 6.0.5 on 2026-05-13 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'سيارة', 'verbose_name_plural': 'السيارات'},
        ),
        migrations.AlterModelOptions(
            name='carfeature',
            options={'verbose_name': 'ميزة', 'verbose_name_plural': 'ميزات السيارات'},
        ),
        migrations.AlterModelOptions(
            name='carimage',
            options={'verbose_name': 'صورة سيارة', 'verbose_name_plural': 'صور السيارات'},
        ),
        migrations.AlterModelOptions(
            name='officeinfo',
            options={'verbose_name': 'معلومات المكتب', 'verbose_name_plural': 'معلومات المكتب'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'رابط تواصل', 'verbose_name_plural': 'روابط التواصل'},
        ),
        migrations.AlterField(
            model_name='car',
            name='body_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع الهيكل'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='الماركة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, max_length=50, verbose_name='اللون'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.CharField(blank=True, max_length=50, verbose_name='حجم المحرك'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع الوقود'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشطة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='سيارة مميزة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='mileage',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الكيلومترات'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(max_length=100, verbose_name='الموديل'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='السعر'),
        ),
        migrations.AlterField(
            model_name='car',
            name='seats',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد المقاعد'),
        ),
        migrations.AlterField(
            model_name='car',
            name='status',
            field=models.CharField(choices=[('available', 'متوفرة'), ('sold', 'مباعة'), ('reserved', 'محجوزة')], default='available', max_length=20, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='title',
            field=models.CharField(max_length=200, verbose_name='عنوان السيارة'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, max_length=50, verbose_name='نوع الجير'),
        ),
        migrations.AlterField(
            model_name='car',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر تعديل'),
        ),
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.PositiveIntegerField(verbose_name='سنة الصنع'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='cars.car', verbose_name='السيارة'),
        ),
        migrations.AlterField(
            model_name='carfeature',
            name='name',
            field=models.CharField(max_length=100, verbose_name='الميزة'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='السيارة'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=models.ImageField(upload_to='cars/', verbose_name='الصورة'),
        ),
        migrations.AlterField(
            model_name='carimage',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='الصورة الرئيسية'),
        ),
        migrations.AlterField(
            model_name='officeinfo',
            name='address',
            field=models.TextField(blank=True, verbose_name='العنوان'),
        ),
        migrations.AlterField(
            model_name='officeinfo',
            name='description',
            field=models.TextField(blank=True, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='officeinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='البريد الإلكتروني'),
        ),
        migrations.AlterField(
            model_name='officeinfo',
            name='name',
            field=models.CharField(max_length=150, verbose_name='اسم المكتب'),
        ),
        migrations.AlterField(
            model_name='officeinfo',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='رقم الهاتف'),
        ),
        migrations.AlterField(
            model_name='officeinfo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=30, verbose_name='رقم الواتساب'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='نشط'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='platform',
            field=models.CharField(choices=[('facebook', 'فيسبوك'), ('instagram', 'إنستغرام'), ('whatsapp', 'واتساب'), ('telegram', 'تلغرام'), ('tiktok', 'تيك توك'), ('website', 'موقع إلكتروني')], max_length=50, verbose_name='المنصة'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='url',
            field=models.URLField(verbose_name='الرابط'),
        ),
    ]
