# Generated by Django 6.0.5 on 2026-05-13 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_alter_car_options_alter_carfeature_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='cars/videos/', verbose_name='فيديو السيارة'),
        ),
        migrations.DeleteModel(
            name='CarFeature',
        ),
    ]
